---
- name: Server reboot
  hosts: all
  become: yes
  become_user: root
  tasks:
    - name: reboot
      reboot:
        msg: "Rebooting the servers"
        connect_timeout: 5
        reboot_timeout: 300
        pre_reboot_delay: 0
        post_reboot_delay: 30